### PR TITLE
Add charlesrotation point offset issue #56

### PR DESCRIPTION
**Pull request by frenchcdsl44**
I eventually called the method offsetCenterPoint because setting the centre (ex-centred) would require to define if it is from the container's or the element's origin. Here the origin is the controls' centre.

It works fine when the option rotationPoint is defined. 

A unit test might be useful but I did not see an example to use as a base

Don't hesitate to tell me if you need more help. I continue learning.

### CODE REVIEW

**Comment by nichollascarter** [comment]
Let's clarify the purpose, you need to set **absolute** or **relative** values for center offset?

Looks like you removed `resetCenterPoint`, i don't think it is correct at this step.

**Comment by nichollascarter** [comment]
Let's clarify the purpose, you need to set absolute or relative values for center offset?

**Comment by frenchcdsl44** [comment]
Sorry I was not clear. The proposed function is offsetCenterPoint(x,y). So it shifts the rotation center of x and y relatively to the default center (determined, as I understand it, by the element's width/2 and height/2)

I thought of setCenterPoint(x,y) but yes it would require to define whether it is absolute or relative and I am not familiar enough with the code to make it.

My final need is to make a kind of puppet made of svg elements and to be able to rotate the limbs (a bit like http://fabricjs.com/stickman). I intend to opensource the code.

**Comment by frenchcdsl44** [comment]
thanks again for #64

**Pull request closed without merging**
